im1 = imread('retina.jpg');
im2 = imread('retina_template.bmp');
im1_2gray = rgb2gray(im1);
SE = strel('disk',10);
J = imclose(im1_2gray,SE);
CO = J - im1_2gray;
% figure(4); imshow(CO);
COI = adapthisteq(CO);
% figure(3); imshow(COI);
BW_im1 = im2bw(COI,0.21);
% figure(3); imshow(BW_im1);
mask = and(BW_im1,im2);
% figure(1); imshow(mask);
SE2 = strel('square',2);
marker = imerode(mask,SE2);
output1 = imreconstruct(marker,mask);
figure(1); imshow(output1);
output2 = drawVessel(im1_2gray,output1);
figure(2); imshow(output2);
imwrite(output1,'recon_output.jpg');
imwrite(output2,'drawVessel_output.jpg');